### ISSUE TITLE
InterTravel - Internationally Traveling activites and Planning

### ISSUE THREAD

**Issue by Rbojja23** [Kiruthic-Selvakumar/travel_frontend#1]
# **InterTravel**
## Objective

To create a social media platform where planning for international travel procedures is made simpler and accessible. To provide users with a detailed and user-friendly tool that offers insights into various elements of planning travel or vacation, including destination activities, food, hotels, transportation, budget, packing, and healthcare, enabling them to make informed decisions.

InterTravel will include great analytics/ratings for users making deciding the best spots to go on while on vacation extremely easy. The website will make use of AI to respond to user posts and questions regarding a specific place or attraction. Finally, by including the costs as a part of the decision-making InterTravel drives a great package deal of a one-spot webpage capable of supplying users with everything they need to go on a stress-free vacation.

**Specifically in 5 Popular Destinations: Hong Kong, Mumbai, London, New York, Paris**

### 1. **Rate Analytics**

A robust rating system allows users to score destinations, restaurants, and attractions on a scale of 1-10.
Advanced analytics highlight top-rated and trending spots, helping users choose the best options easily.

### 2. **Interactive Social Features**

Users can post detailed reviews, and engage in discussions with other travelers through comments and Q&A.

### 3. **Cost and Budget Tools**

It will have cost comparisons for accommodations, activities, and transportation, with a built-in budget planner to simplify travel expenses.

### 4. **API Integration**

APIs handle reviews, ratings, and AI responses, ensuring seamless functionality and interactivity across the platform.

---

## Organization

The organization will include a user login, and authentication. A travel home page outlining the different features available to help users, and provide links in the main cities that lead to the tools. Each individual feature of InterTravel(e.g. food or hotel) will have its own page with full-stack functionality and ability to make posts as well as rate.

## Emphasis on Social Media and Interaction

Along with features to help plan such as a destination planner, most tools and pages on InterTravel will have ability for users to be able to post comments/reviews about a specific destination and review their quality of service. Attached to their review, the website will also have a rate functionality, where users will be able to rate a destination or place on a scale of 1-10, and that average will be displayed so users can best choose where they stay or go out to eat, for example.

- Post/Review Functionality
- Rate(1-10) average Functionality
- Display Cost Functionality
- Allows for potential customers to ask questions to those who have used the products.

---
<img width="925" alt="Screenshot 2024-12-03 at 8 55 12 AM" src="https://github.com/user-attachments/assets/b6830d50-703d-4854-aff4-4fad81029f7f">

## **Topics and Tools**
- **Home Page**: Prompts user to log in, user-friendly, minimalistic design
- **Sub-Section Cities**: Includes each destination (Hong Kong, Paris, New York, Mumbai, London)

**City Sub-Sections Include**
- **Budget Planning (Derek):** Users can plan specific costs per day and plan their budgets for travel.
- **Health Insurance (Arhaan)**: allows for a day-to-day planning system where users can clearly make a methodology for their trip.
- **Travel Methods (Rohan)**: allows for a clear understanding of different methods of travel, along with fares and costs, as well as time, etc.
- **Places to stay (Aadi):** Offers user an exhaustive list of regions and specific areas of where to stay during their travels while also being integrated into the daily planning.
- **Food Options (Tarun):** Give the user a large list of food options near the area, as well as the different meal genres and specific filters for vegetarians, etc. It also takes into account the prices of the food options.
- **Available Activities or Destination Imagination (Kiruthic):** By scouting out the area near the region of interest, the user will be given a list of activities to complete.
- **Packing (Aditya):** The user will be able to look at lists of packing and look at certain guidelines for travel for specific packing requirements.

All features will include post/review functionality, and some will include rate functionality.

---
## **Team Roles**  

| **Role**                 | **Team Member** | **Assignments**           | **Contribution**                                                                                       |  
|--------------------------|-----------------|---------------------------|--------------------------------------------------------------------------------------------------------|  
| **Scrum Master**         | Kiruthic        | Destination Activities    | Prune/organize repository, configure AI API, work on Rate API, complete full-stack code for page, guide team, provide requirements |  
| **Scrummer #2**          | Rohan           | Transportation            | Complete full-stack code for page, create plan designs, integrate AI API                              |  
| **Scrummer #3**          | Tarun           | Food                      | Complete full-stack code for page, design and contribute to Rate API                                  |  
| **Assistant Scrum Master**| Aadi           | Hotels                    | Complete full-stack code for page, coordinate with scrummers, contribute to Rate API                  |  
| **Scrummer #5**          | Derek           | Budget                    | Complete full-stack code for page                                                                     |  
| **Scrummer #6**          | Aaditya         | Packing                   | Complete full-stack code for page                                                                     |  
| **Scrummer #7**          | Arhaan          | Healthcare                | Complete full-stack code for page, integrate AI API                                                   |  

  
---
## **CPT Requirments**

| **Big Idea**                                  | **Implementations**                                                                                                                                               |
|------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Collaboration, Program Function, and Purpose  | Team Issue, planning with Kanban, team roles and check-ins                                                                                                        |
| Program Design and Development                | Ensure front-backend connection works well, enhance user experience from Flocker                                                                                 |
| Debugging Code and Fixing Errors              | Take user feedback and use it to improve features, use interceptors to debug while coding                                                                          |
| Data                                           | Utilize Google Travel APIs or similar to find databases for locations and establish fetching connection with frontend and backend.                                 |
| Deployment and Internet Concepts              | Login features, uniform domain system, fetch different API requests, organize to make code simple and optimize performance                                      |
| Data Science and Social Media                 | Allows logged-in users to make posts on different sections that will be cached in the backend database, analyzing data using Python libraries                      |

---
## **Repositories**

Frontend: https://github.com/Kiruthic-Selvakumar/travel_frontend
Backend: https://github.com/Kiruthic-Selvakumar/travel_backend

## **Webpage**
https://kiruthic-selvakumar.github.io/travel_frontend/

---
## **Frontend to Backend Integration**

 In specific, due to the nature and idea of InterTravel, specific API will need to be used to store user data, and provide analytics to users(Just feature-specific)
API's:

- Post API to create reviews and ask questions regarding travel(destinations, etc.)
- New Rate API to allow users to rate a specific destination or spot shown on our site.
- Make use of ChatGPT or Gemini API to respond to user questions

---
## **Figma Design**

![image](https://github.com/user-attachments/assets/a622e129-ea8a-4009-9f97-52e3173840e2)
![image](https://github.com/user-attachments/assets/83fbeca6-359a-4f43-885c-d0804cec5352)
![image](https://github.com/user-attachments/assets/43ff712a-fea2-4a99-9d35-312204c95553)
![image](https://github.com/user-attachments/assets/7a874c47-697d-4e36-8a5b-c32a47bd4b95)

---
## **To-do**

- [x] Clone Frontend and Backend Repos
- [x] Purge Frontend and Backend to make clear unused files
- [x] Assign team roles and organization structure
- [x] Ideate on site with team/personal issues and figma design
- [x] Implement frontend figma design
- [ ] Integrate Log-in system with customizable profile and additional features for logged in users
- [ ] Find and implement travel APIs into backend
- [ ] Work on Frontend-backend connection and ensure smooth and user-friendly experience when interacting with backend data
- [ ] Ask for user feedback and improve from there

---
## **Kanban**

https://github.com/users/Kiruthic-Selvakumar/projects/2

**Comment by tarunrayavarapu** [comment]
https://github.com/tarunrayavarapu/tarun_2025/issues/10

(link to issue)

**Comment by Rbojja23** [comment]
Fair Fares (Rohan Bojja) Planning Issue: https://github.com/Rbojja23/rohan_2025/issues/10

**Comment by ArhaanM123** [comment]
Wellness Waypoints(Arhaan Memon) Issure
https://github.com/ArhaanM123/Arhaan_2025/issues/14

**Comment by aadibhat09** [comment]
Lodging Listings issue
https://github.com/aadibhat09/aadi_2025/issues/21

**Comment by derekkang1** [comment]
Budgeting Brilliance (Derek K)
[](https://github.com/derekkang1/DerekCSP/issues/8)

**Comment by aadityataleppady** [comment]
Packing Portal issue (Aaditya Taleppady): https://github.com/aadityataleppady/aaditya_2025/issues/6#issue-2682066304

**Comment by Kiruthic-Selvakumar** [comment]
[Destination Imagination Plan](https://github.com/Kiruthic-Selvakumar/Kiruthic_student_2025/issues/7) (Kiruthic Selvakumar)

**Comment by jm1021** [comment]
This is a lot.  You certainly have taken project seriously and considered many travel considerations and breakdowns.   You could probably scale down.   On this type of thing, you could socially plan a trip to a few places considering your many idea.  

For instance pick top five destinations where you think people may want to go and consider many ideas and build a chat room and travel planner to ...

Paris
Rome
Shanghai
Hyderabad
New York

.91 mostly for vast brain storming, but unless you scale down it will not happen.
