### ISSUE TITLE
Backend ToDo

### ISSUE THREAD

**Issue by Rbojja23** [Kiruthic-Selvakumar/travel_frontend#18]
Checklist:

- [x] Root level app.py implementation
- [x] Implement all user APIs
- [x] Test all user APIs with port given
- [ ] Make a big server with the database ()
- [ ] Frontend to backend connection (Brought in through the about me page)
- [ ] Creating dynamic database
